module-name: kim-snatch
kind: kyma
bdba:
  - europe-docker.pkg.dev/kyma-project/prod/kim-snatch:latest
mend:
  language: golang-mod
  exclude:
    - "**/*_test.go"
checkmarx-one:
    preset: go-default
    exclude:
        - '**/*_test.go'
