name: KIM-Snatch Release

on:
  push:
    tags:
      - '*'  # Trigger on tag pushes

jobs:
  run-release-tests:
    permissions:
      contents: read
    uses: ./.github/workflows/tests.yml

  generate-release:
    needs: run-release-tests
    if: needs.run-release-tests.result == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases and uploading assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Generate Release module artifacts for tag release
        run: |
          set -e
          make build-installer 
          cp ./dist/kim-snatch.yaml kim-snatch.yaml
        env:
          IMG: europe-docker.pkg.dev/kyma-project/prod/kim-snatch:${{ github.ref_name }}

      - name: Generate Release module artifacts for experimental tag release
        run: |
          set -e
          make build-installer
          cp ./dist/kim-snatch.yaml kim-snatch-experimental.yaml
        env:
          IMG: europe-docker.pkg.dev/kyma-project/prod/kim-snatch:${{ github.ref_name }}-experimental

      - name: Create Release and Generate Notes
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./kim-snatch.yaml
            ./kim-snatch-experimental.yaml
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-release-report:
    needs: generate-release
    if: needs.generate-release.result == 'success'
    permissions:
      actions: read
      contents: read
    uses: ./.github/workflows/upload-release-report.yaml
    with:
      release_version: ${{ github.ref_name }}
    secrets:
      RELEASE_LOG_UPLOADER_SA: ${{ secrets.RELEASE_LOG_UPLOADER_SA }}
